name: Continuous Delivery

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ios:
    name: iOS
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.1"
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path:
            "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      - name: Install Dependencies
        run: |
          flutter pub get

      - name: Lint Flutter
        run: |
          flutter analyze --fatal-infos

      - name: Build
        run: |
          flutter config --enable-ios
          flutter config --enable-swift-package-manager
          flutter build ipa --no-codesign

  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        run: echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.1"
          channel: "stable"
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path:
            "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - name: Install Dependencies
        run: |
          flutter pub get

      - name: Lint Flutter
        run: |
          dart analyze --fatal-infos

      - name: Build
        run: |
          flutter config --enable-android
          flutter build appbundle
